//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamApp.OnlineExamAppServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnlineExamAppServiceReference.IOnlineExamAppService")]
    public interface IOnlineExamAppService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineExamAppService/GetQuestion", ReplyAction="http://tempuri.org/IOnlineExamAppService/GetQuestionResponse")]
        object GetQuestion(System.Nullable<int> questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineExamAppService/GetQuestion", ReplyAction="http://tempuri.org/IOnlineExamAppService/GetQuestionResponse")]
        System.Threading.Tasks.Task<object> GetQuestionAsync(System.Nullable<int> questionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnlineExamAppServiceChannel : OnlineExamApp.OnlineExamAppServiceReference.IOnlineExamAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineExamAppServiceClient : System.ServiceModel.ClientBase<OnlineExamApp.OnlineExamAppServiceReference.IOnlineExamAppService>, OnlineExamApp.OnlineExamAppServiceReference.IOnlineExamAppService {
        
        public OnlineExamAppServiceClient() {
        }
        
        public OnlineExamAppServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineExamAppServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineExamAppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineExamAppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object GetQuestion(System.Nullable<int> questionId) {
            return base.Channel.GetQuestion(questionId);
        }
        
        public System.Threading.Tasks.Task<object> GetQuestionAsync(System.Nullable<int> questionId) {
            return base.Channel.GetQuestionAsync(questionId);
        }
    }
}
